[package]
name = "shared"
version = "0.1.0"
edition = "2024"

[dependencies]
serde.workspace = true
chrono.workspace = true
figment.workspace = true
thiserror.workspace = true
sqlx.workspace = true
tracing.workspace = true

[dev-dependencies]
reqwest.workspace = true
tokio.workspace = true
